bayes_people_tracker:
    filter_type: "UKF"                                         # The Kalman filter type: EKF = Extended Kalman Filter, UKF = Uncented Kalman Filter
    cv_noise_params:                                           # The noise for the constant velocity prediction model
        x: 3.0
        y: 3.0
        z: 3.0
    detectors:                                                 # Add detectors under this namespace
        left_tracker:                                   # Name of detector (used internally to identify them). Has to be unique.
            topic: "/to_pose_array/circle_detector_left" # The topic on which the geometry_msgs/PoseArray is published
            cartesian_noise_params:                            # The noise for the cartesian observation model
                x: 0.05
                y: 0.05
                z: 0.05
            matching_algorithm: "NNJPDA"                       # The algorthim to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
        right_tracker:                                          # Name of detector (used internally to identify them). Has to be unique.
            topic: "/to_pose_array/circle_detector_right"               # The topic on which the geometry_msgs/PoseArray is published
            cartesian_noise_params:                            # The noise for the cartesian observation model
                x: 0.05
                y: 0.05
                z: 0.05
            matching_algorithm: "NNJPDA"                       # The algorthim to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
